change toc and preempt overwrite
Azure/azure-docs-sdk-java pull request #1444
Opened 2020-11-11 19:27 UTC by PatrickFarley

2020-11-11 19:47 UTC, opbld32 commented
Docs Build status updates of commit _[7d34dc3](https://github.com/PatrickFarley/azure-docs-sdk-java/commits/7d34dc34719d59ec37fb9af72ea30c9ad58de543)_: 

:clock10: **Full build**: the average full build time is _328 min(s) 30 sec(s)_, this is based on the last _1000_ build(s) for this repository.

2020-11-12 06:04 UTC, opbld32 commented
Docs Build status updates of commit _[7d34dc3](https://github.com/PatrickFarley/azure-docs-sdk-java/commits/7d34dc34719d59ec37fb9af72ea30c9ad58de543)_: 

:clock10: **Full build**: the average full build time is _328 min(s) 30 sec(s)_, this is based on the last _1000_ build(s) for this repository.

2020-11-12 16:26 UTC, opbld31 commented
Docs Build status updates of commit _[7d34dc3](https://github.com/PatrickFarley/azure-docs-sdk-java/commits/7d34dc34719d59ec37fb9af72ea30c9ad58de543)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/resourcemanager-msi-readme.md](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/docs-ref-services/resourcemanager-msi-readme.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-msi-readme?view=azure-java-stable&branch=pr-en-us-1444) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-msi-readme?view=azure-java-preview&branch=pr-en-us-1444) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-msi-readme?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-0b69189c-24096e98)
[docs-ref-services/virtualmachines.md](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/docs-ref-services/virtualmachines.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/virtualmachines?view=azure-java-stable&branch=pr-en-us-1444) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/virtualmachines?view=azure-java-preview&branch=pr-en-us-1444) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/virtualmachines?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-9994c506-24096e98)
[docs-ref-services/resourcemanager-appservice-readme.md](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/docs-ref-services/resourcemanager-appservice-readme.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-appservice-readme?view=azure-java-stable&branch=pr-en-us-1444) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-appservice-readme?view=azure-java-preview&branch=pr-en-us-1444) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-appservice-readme?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-83c62f03-24096e98)
[docs-ref-services/resources.md](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/docs-ref-services/resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resources?view=azure-java-stable&branch=pr-en-us-1444) (azure-java-stable)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resources?view=azure-java-preview&branch=pr-en-us-1444) (azure-java-preview)<br/> [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/resources?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-7d0fce31-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingVideoSearch.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingVideoSearch.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingvideosearch?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-dfd967a4-24096e98)
[legacy/docs-ref-autogen/overview/ContainerService.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/ContainerService.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/containerservice?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-e256176e-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingWebSearchAPI.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingWebSearchAPI.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingwebsearchapi?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-742fb9fb-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingAutoSuggest.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingAutoSuggest.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingautosuggest?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-70d11aac-24096e98)
[legacy/docs-ref-autogen/overview/EventHubs/Client.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/EventHubs/Client.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/eventhubs/client?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-30db23b8-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingVisualSearch.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingVisualSearch.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingvisualsearch?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-fe166329-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingCustomImageSearch.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingCustomImageSearch.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingcustomimagesearch?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-e814ee09-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingImageSearch.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingImageSearch.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingimagesearch?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-e33370ed-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingEntitySearchAPI.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingEntitySearchAPI.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingentitysearchapi?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-89f51c90-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingNewsSearch.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingNewsSearch.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingnewssearch?view=azure-java-legacy&branch=pr-en-us-1444) (azure-java-legacy) | [Details](#user-content-df9d7d1a-24096e98)
[legacy/docs-ref-autogen/overview/cognitiveservices/client/BingCustomSearch.yml](https://github.com/PatrickFarley/azure-docs-sdk-java/blob/master/legacy/docs-ref-autogen/overview/cognitiveservices/client/BingCustomSearch.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/bingc [...]

2020-11-12 19:20 UTC, sima-zhu commented
Could you change the target branch to smoke-test instead of master? We do not merge any changes to master directly. We use smoke-test as our gating branch. Thanks!

2020-11-12 19:21 UTC, sima-zhu requested changes
Please change the target branch to smoke-test. Thanks!

2020-11-13 17:55 UTC, closed without merging

2020-11-13 17:57 UTC, PatrickFarley commented
https://github.com/Azure/azure-docs-sdk-java/pull/1461